const nav = [
  ['Cursos','/cursos/'],['Cambridge','/cambridge/'],['Método','/metodologia/'],['Nosotros','/sobre-nosotros/'],['Matrícula','/matricula/']
];

const icon = (name='arrow') => {
 const icons={
  arrow:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',
  check:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 6 9 17l-5-5"/></svg>',
  pin:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>',
  phone:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M22 16.9v3a2 2 0 0 1-2.2 2A19.8 19.8 0 0 1 3 5.2 2 2 0 0 1 5 3h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.4 2.1L9 11a16 16 0 0 0 4 4l1.3-1.3a2 2 0 0 1 2.1-.4c.9.3 1.9.6 2.9.7a2 2 0 0 1 1.7 2Z"/></svg>',
  mail:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg>',
  insta:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg>',
  clock:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',
  chat:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.2 9.2 0 0 1-4-.9L3 21l1.7-4.7A8.4 8.4 0 1 1 21 11.5Z"/></svg>'
 };
 return icons[name]||icons.arrow;
};

export const header = () => `
<header class="site-header"><div class="header-inner">
<a class="wordmark" href="/" aria-label="Cosmo School - inicio"><img src="/images/logo-web.webp" alt="Cosmo School"><small>ACADEMIA DE INGLÉS · ÉCIJA</small></a>
<nav class="desktop-nav">${nav.map(([l,h])=>`<a href="${h}">${l}</a>`).join('')}</nav>
<a class="header-cta" href="/contacto/">Habla con nosotros ${icon('arrow')}</a>
<button class="menu-btn" aria-label="Abrir menú" data-menu>MENU</button>
</div><div class="mobile-menu" data-mobile-menu>${nav.map(([l,h])=>`<a href="${h}">${l}</a>`).join('')}<a href="/contacto/">Habla con nosotros</a></div></header>`;

export const footer = () => `
<footer class="footer"><div class="footer-lead wrap"><div><span class="eyebrow light">Écija · Sevilla</span><h2>El inglés abre puertas.<br>Empecemos por la primera.</h2></div><a href="/matricula/" class="round-link">Solicitar información ${icon('arrow')}</a></div>
<div class="footer-grid wrap"><div class="footer-brand"><img src="/images/logo-web.webp" alt="Cosmo School"><p>Academia de inglés en Écija desde 2015.</p></div><div><h4>Explora</h4><a href="/cursos/">Cursos</a><a href="/cambridge/">Cambridge</a><a href="/metodologia/">Método</a><a href="/sobre-nosotros/">Nosotros</a></div><div><h4>Contacto</h4><a href="tel:+34643349226">${icon('phone')} 643 349 226</a><a href="mailto:cosmoschool2015@gmail.com">${icon('mail')} cosmoschool2015@gmail.com</a><a href="https://instagram.com/cosmoschool2015" target="_blank">${icon('insta')} @cosmoschool2015</a></div><div><h4>Centros</h4><p>${icon('pin')} C/ Merinos, 54<br>41400 Écija</p><p>${icon('pin')} C/ Fuente Nueva, 2<br>41400 Écija</p></div></div>
<div class="footer-bottom wrap"><span>© 2026 Cosmo School · Concepto digital</span><div><a href="/legal/">Aviso legal</a><a href="/legal/#privacidad">Privacidad</a><a href="/legal/#cookies">Cookies</a></div></div></footer>`;

const form = (compact=false) => `<form class="lead-form ${compact?'compact':''}" data-lead-form><div class="form-fields"><div class="field"><label>Nombre</label><input required placeholder="Tu nombre"></div><div class="field"><label>Teléfono</label><input required type="tel" placeholder="600 000 000"></div><div class="field"><label>Estoy buscando…</label><select required><option value="">Selecciona una opción</option><option>Inglés para niños</option><option>Adolescentes</option><option>Adultos</option><option>Preparación Cambridge</option><option>Clases one to one</option><option>Curso intensivo</option></select></div>${compact?'':'<div class="field"><label>Cuéntanos un poco más</label><textarea rows="4" placeholder="Nivel aproximado, edad, disponibilidad…"></textarea></div>'}<label class="consent"><input type="checkbox" required> He leído y acepto la política de privacidad.</label><button class="button primary full" type="submit">Quiero información ${icon('arrow')}</button></div><div class="form-success" hidden><span>${icon('check')}</span><h3>Solicitud preparada</h3><p>En la web final, este formulario se conectaría directamente con la academia. En este prototipo puedes continuar por WhatsApp.</p><a class="button primary" target="_blank" href="https://wa.me/34643349226?text=Hola%20Cosmo%20School,%20quiero%20información%20sobre%20la%20matrícula.">Continuar por WhatsApp</a></div></form>`;

const pageHero=(e,t,d,img)=>`<section class="page-hero" data-page-mode="Explore"><div class="page-hero-copy wrap"><span class="eyebrow">${e}</span><h1>${t}</h1><p>${d}</p><a class="text-link" href="/matricula/">Solicitar información ${icon('arrow')}</a></div>${img?`<div class="page-hero-image"><img src="${img}" alt=""></div>`:''}</section>`;

const shell=(title,body)=>`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Cosmo School, academia de inglés en Écija. Inglés para niños, adolescentes y adultos. Preparación Cambridge."><title>${title} | Cosmo School</title><link rel="stylesheet" href="/styles.css"><link rel="icon" href="data:,"></head><body data-motion="ready">${header()}<main>${body}</main>${footer()}<a class="float-contact" href="https://wa.me/34643349226?text=Hola%20Cosmo%20School,%20quiero%20información%20sobre%20vuestros%20cursos." target="_blank" aria-label="WhatsApp">${icon('chat')}<span>WhatsApp</span></a><script src="/app.js"></script></body></html>`;

const home=()=>shell('Academia de inglés en Écija',`
<section class="hero-home" data-page-mode="Atmosphere"><div class="hero-media"><img src="https://academiacosmoschool.com/wp-content/uploads/2023/03/Rectangle-255-1516x652.png" alt="Estudiantes conversando"><div class="hero-overlay"></div></div><div class="hero-content wrap"><div class="hero-kicker"><span>Écija · Desde 2015</span><span>Preparación Cambridge</span></div><h1>Inglés para<br><em>llegar más lejos.</em></h1><div class="hero-bottom"><p>Una academia cercana, exigente y humana para aprender inglés con confianza, desde los 4 años hasta C2.</p><a href="/matricula/" class="button light">Solicitar información ${icon('arrow')}</a></div></div><div class="hero-stamp"><strong>10+</strong><span>años<br>enseñando</span></div></section>
<section class="intro-band"><div class="wrap intro-grid"><span class="eyebrow">COSMO SCHOOL / ÉCIJA</span><h2>No enseñamos para aprobar un tema.<br><em>Enseñamos para usar el idioma.</em></h2><p>Profesionales bilingües y cualificados, clases para todas las edades y una metodología que combina preparación académica, conversación y acompañamiento real.</p></div></section>
<section class="programs-section wrap" data-reveal-section><div class="section-heading split"><div><span class="eyebrow">Encuentra tu camino</span><h2>Un curso para cada etapa.</h2></div><a href="/cursos/" class="text-link">Ver todos los cursos ${icon('arrow')}</a></div><div class="program-grid">
${[['01','Kids','Desde 4 años','Aprender inglés jugando, hablando y perdiendo el miedo desde el primer día.','/cursos/'],['02','Teens','Adolescentes','Más soltura, mejores resultados y preparación académica con un inglés que se usa de verdad.','/cursos/'],['03','Adults','Adultos','Clases presenciales u online para avanzar de nivel con objetivos claros y acompañamiento.','/cursos/'],['04','Cambridge','B1 · B2 · C1 · C2','Preparación específica para exámenes oficiales, con varias convocatorias durante el curso.','/cambridge/']].map(([n,t,s,d,h])=>`<a class="program-card" href="${h}"><div class="program-top"><span>${n}</span><span>↗</span></div><div><small>${s}</small><h3>${t}</h3><p>${d}</p></div><span class="program-arrow">↘</span></a>`).join('')}
</div></section>
<section class="cambridge-feature" data-reveal-section><div class="wrap cambridge-grid"><div class="cambridge-copy"><span class="eyebrow light">Preparación oficial</span><h2>Tu objetivo tiene nombre.<br><em>Cambridge.</em></h2><p>Preparación para B1, B2, C1 y C2 con un curso estructurado de septiembre a junio y un mínimo de 4 convocatorias oficiales durante el curso.</p><div class="level-row"><span>B1</span><span>B2</span><span>C1</span><span>C2</span></div><a class="button light" href="/cambridge/">Cómo preparamos tu examen ${icon('arrow')}</a></div><div class="cambridge-visual"><img src="https://academiacosmoschool.com/wp-content/uploads/2024/03/diccionario-ingles-scaled.jpg" alt="Diccionario de inglés"><div class="visual-note">${icon('check')}<span>Preparación específica<br><strong>por nivel y objetivo</strong></span></div></div></div></section>
<section class="method-section wrap" data-reveal-section><div class="section-heading"><span class="eyebrow">Nuestra forma de enseñar</span><h2>Aprender bien también puede sentirse bien.</h2></div><div class="method-layout"><div class="method-image"><img src="https://academiacosmoschool.com/wp-content/uploads/2017/08/home-1-bg-e1503477367706-1516x652.jpg" alt="Estudiante leyendo"></div><div class="method-list"><div><span>01</span><h3>Grupos y atención cercana</h3><p>Un entorno en el que cada alumno puede participar, preguntar y avanzar con seguimiento.</p></div><div><span>02</span><h3>Inglés que se practica</h3><p>Comprensión, conversación, vocabulario y gramática conectados a situaciones reales.</p></div><div><span>03</span><h3>Progreso con dirección</h3><p>Objetivos claros por nivel para saber qué estás trabajando y hacia dónde vas.</p></div></div></div></section>
<section class="formats-strip" data-reveal-section><div class="wrap formats-grid"><div><span class="format-mark">ON</span><h3>Online</h3><p>Flexibilidad para aprender estés donde estés.</p></div><div><span class="format-mark">IN</span><h3>Presencial</h3><p>Dos centros en Écija y contacto directo con tu profesor.</p></div><div><span class="format-mark">1:1</span><h3>One to one</h3><p>Un plan más específico, adaptado a tus necesidades.</p></div><div><span class="format-mark">30D</span><h3>Intensivos</h3><p>Preparación concentrada para exámenes oficiales.</p></div></div></section>
<section class="abroad-section wrap" data-reveal-section><div class="abroad-card"><img src="https://academiacosmoschool.com/wp-content/uploads/2025/10/filters_quality70-1024x576.webp" alt="Estudiantes en el extranjero"><div class="abroad-overlay"></div><div class="abroad-copy"><span class="eyebrow light">Más allá del aula</span><h2>El idioma cambia cuando lo vives.</h2><p>Cursos de idioma en el extranjero para abrir mundo, ganar autonomía y convertir el inglés en experiencia.</p><a href="https://www.ef.com.es/" target="_blank" class="button light">Explorar programas ${icon('arrow')}</a></div></div></section>
<section class="app-section" data-reveal-section><div class="wrap app-grid"><div class="app-copy"><span class="eyebrow">También en tu móvil</span><h2>Tu curso, más cerca incluso fuera del aula.</h2><p>Cosmo School publica actualmente una app para acompañar la experiencia del alumno. En esta propuesta, el acceso se integra como parte natural del ecosistema digital de la academia, sin competir con la información principal para nuevas matrículas.</p><a class="text-link" href="/contacto/">Consultar acceso a la app ${icon('arrow')}</a></div><div class="app-art"><span class="app-orbit orbit-one"></span><span class="app-orbit orbit-two"></span><div class="phone-shell"><div class="phone-top"></div><img src="/images/logo-web.webp" alt="Cosmo School"><div class="phone-copy"><small>COSMO SCHOOL</small><strong>Keep<br>going.</strong><span>Tu inglés, siempre contigo.</span></div></div></div></div></section><section class="locations-section wrap" data-reveal-section><div class="section-heading split"><div><span class="eyebrow">Estamos cerca</span><h2>Dos centros. Una misma forma de enseñar.</h2></div><p>Atención de recepción de lunes a viernes por la tarde y de martes a viernes por la mañana.</p></div><div class="location-grid"><div class="location-card"><span>01</span>${icon('pin')}<h3>Merinos</h3><p>C/ Merinos, 54<br>41400 Écija, Sevilla</p><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=C%2F%20Merinos%2054%20Ecija">Cómo llegar ${icon('arrow')}</a></div><div class="location-card accent"><span>02</span>${icon('pin')}<h3>Fuente Nueva</h3><p>C/ Fuente Nueva, 2<br>41400 Écija, Sevilla</p><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=C%2F%20Fuente%20Nueva%202%20Ecija">Cómo llegar ${icon('arrow')}</a></div></div></section>
<section class="lead-section" data-reveal-section><div class="wrap lead-grid"><div><span class="eyebrow light">Matrícula e información</span><h2>Cuéntanos qué necesitas.<br><em>Nosotros te orientamos.</em></h2><p>No tienes que saber qué nivel elegir. Dinos para quién son las clases y qué objetivo tienes; el equipo te ayuda a encontrar la opción adecuada.</p></div>${form(true)}</div></section>`);

const cursos=()=>shell('Cursos',`${pageHero('Programas','Inglés para cada edad, objetivo y momento.','No todo el mundo aprende por la misma razón. Por eso Cosmo School combina diferentes formatos y recorridos para que el curso encaje contigo.','https://academiacosmoschool.com/wp-content/uploads/2023/03/Rectangle-255-1516x652.png')}<section class="course-list wrap" data-page-mode="Decide" data-reveal-section>${[
['Inglés para niños','Desde 4 años','Una primera relación positiva con el idioma: aprender, jugar, escuchar y expresarse en inglés con naturalidad.',['Aprendizaje adaptado a la edad','Actividades dinámicas y participativas','Base sólida para seguir creciendo']],
['Adolescentes','Secundaria y Bachillerato','Un espacio para consolidar el nivel académico, ganar soltura y avanzar hacia certificaciones oficiales.',['Refuerzo de todas las destrezas','Preparación orientada a objetivos','Más seguridad al hablar']],
['Adultos','Todos los niveles','Para quien quiere retomar el inglés, mejorar por trabajo, viajar o conseguir una titulación oficial.',['Presencial u online','Ritmo compatible con tu día a día','Objetivos claros por nivel']],
['One to one','Atención individual','Clases individuales por las mañanas para necesidades específicas que requieren un plan más personalizado.',['Plan adaptado','Atención 100% individual','Objetivos concretos']],
['Clases online','Más flexibilidad','Una alternativa para aprender sin desplazarte, con la posibilidad de recibir grabación si no puedes asistir.',['Desde cualquier lugar','Seguimiento del curso','Grabaciones cuando corresponda']],
['Cursos intensivos','Aprox. 1 mes','Preparación intensiva para exámenes oficiales Cambridge B1, B2, C1 y C2.',['Trabajo concentrado','Foco en examen oficial','B1 · B2 · C1 · C2']]
].map((x,i)=>`<article class="course-row"><div class="course-index">0${i+1}</div><div class="course-icon">${String(i+1).padStart(2,'0')}</div><div class="course-main"><span>${x[1]}</span><h2>${x[0]}</h2><p>${x[2]}</p></div><ul>${x[3].map(p=>`<li>${p}</li>`).join('')}</ul></article>`).join('')}</section><section class="cta-panel wrap"><div><span class="eyebrow light">¿No sabes cuál elegir?</span><h2>Te ayudamos a encontrar tu curso.</h2></div><a href="/matricula/" class="button light">Solicitar orientación ${icon('arrow')}</a></section>`);

const cambridge=()=>shell('Cambridge',`${pageHero('Cambridge English','Un examen importante necesita una preparación a su altura.','Preparación para B1, B2, C1 y C2 con trabajo específico de las destrezas que encontrarás en el examen y un mínimo de 4 convocatorias oficiales a lo largo del curso.','https://academiacosmoschool.com/wp-content/uploads/2024/03/diccionario-ingles-scaled.jpg')}<section class="levels-section wrap" data-page-mode="Decide" data-reveal-section><div class="section-heading split"><div><span class="eyebrow">Tu siguiente nivel</span><h2>De B1 a C2, paso a paso.</h2></div><p>El nivel adecuado depende de tu punto de partida y de tu objetivo. La academia te orienta antes de empezar.</p></div><div class="level-cards">${[['B1','Independent user','Construye una base funcional para desenvolverte en situaciones cotidianas.'],['B2','Upper intermediate','Gana precisión y soltura para estudiar, trabajar y comunicarte con más autonomía.'],['C1','Advanced','Lleva tu inglés a un nivel avanzado, flexible y eficaz en contextos exigentes.'],['C2','Proficiency','Perfecciona comprensión y expresión hasta un dominio muy alto del idioma.']].map(([l,s,d])=>`<div class="level-card"><span>${s}</span><strong>${l}</strong><p>${d}</p>${icon('check')}</div>`).join('')}</div></section><section class="exam-process" data-reveal-section><div class="wrap"><span class="eyebrow light">Preparación completa</span><h2>Entrenar el examen sin dejar de aprender inglés.</h2><div class="process-grid">${[['01','Diagnóstico','Partimos de tu nivel y del objetivo que quieres conseguir.'],['02','Trabajo por destrezas','Reading, writing, listening y speaking dentro de una progresión clara.'],['03','Formato de examen','Practicar tareas y tiempos para llegar con familiaridad y estrategia.'],['04','Convocatoria','El curso contempla varias oportunidades oficiales durante el año académico.']].map(x=>`<div><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div></div></section><section class="centered-cta wrap"><span class="eyebrow">Siguiente convocatoria</span><h2>¿Quieres preparar tu título Cambridge?</h2><p>Cuéntanos tu nivel aproximado y te orientamos sobre la opción más adecuada.</p><a href="/matricula/" class="button primary">Pedir información ${icon('arrow')}</a></section>`);

const metodologia=()=>shell('Metodología',`${pageHero('Metodología','Aprender inglés es ganar confianza para usarlo.','La enseñanza en Cosmo School parte de una idea sencilla: el idioma se consolida cuando se comprende, se practica y se convierte en una herramienta propia.','https://academiacosmoschool.com/wp-content/uploads/2017/08/home-1-bg-e1503477367706-1516x652.jpg')}<section class="principles wrap" data-page-mode="Story" data-reveal-section><div class="section-heading"><span class="eyebrow">Principios</span><h2>Una metodología con intención.</h2></div><div class="principle-grid">${[['01','Comunicación','El inglés se trabaja para entender y expresarse, no solo para completar ejercicios.'],['02','Objetivos claros','Cada etapa responde a un nivel y a metas concretas de progreso.'],['03','Participación','Clases dinámicas que invitan a preguntar, practicar y perder el miedo.'],['04','Acompañamiento','Un equipo cercano que conoce al alumno y puede orientarlo durante el curso.']].map(x=>`<div class="principle"><span class="principle-number">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div></section><section class="editorial-split"><div class="editorial-image"><img src="https://academiacosmoschool.com/wp-content/uploads/2017/08/pexels-photo-40120-e1500018015404-1.jpg" alt="Clase personalizada"></div><div class="editorial-copy"><span class="eyebrow light">No todos aprendemos igual</span><h2>Una misma meta puede necesitar caminos distintos.</h2><p>Niños, adultos, preparación Cambridge, clases online o atención individual. Cambian los formatos, pero se mantiene la intención: que cada alumno avance con una experiencia clara, útil y humana.</p><blockquote>“Cosmo School no es solo una academia de inglés; es un hogar para quienes buscan alcanzar sus sueños a través del poder del lenguaje.”</blockquote><span class="quote-source">— Filosofía de Cosmo School</span></div></section>`);

const nosotros=()=>shell('Sobre nosotros',`${pageHero('Sobre Cosmo School','Una academia de Écija que lleva creciendo desde 2015.','Cosmo School nació con una vocación clara: enseñar inglés con calidad, cercanía y una mirada puesta en el futuro de cada alumno.','https://academiacosmoschool.com/wp-content/uploads/2017/09/home4-gallery.jpg')}<section class="story wrap" data-page-mode="Story" data-reveal-section><div class="story-year">2015</div><div class="story-copy"><span class="eyebrow">Nuestra historia</span><h2>De proyecto educativo a comunidad.</h2><p>Desde su fundación, Cosmo School ha crecido junto a sus alumnos y familias. El proyecto se ha desarrollado manteniendo un compromiso con la excelencia académica, la innovación pedagógica y una enseñanza adaptada a las necesidades de cada estudiante.</p><p>Hoy cuenta con dos centros en Écija y un equipo de profesionales bilingües oficialmente cualificados con experiencia en la enseñanza del inglés como segunda lengua.</p></div></section><section class="values-section"><div class="wrap values-grid"><div><span class="eyebrow light">Lo que importa</span><h2>El alumno en el centro.</h2></div><div class="values-list">${['Respeto por el ritmo y singularidad de cada estudiante','Excelencia académica sin perder cercanía','Confianza, creatividad y comunicación efectiva','Metodologías y herramientas que evolucionan con el mundo'].map(x=>`<div>${icon('check')}<span>${x}</span></div>`).join('')}</div></div></section><section class="team-note wrap"><span class="eyebrow">El equipo</span><h2>Profesionales bilingües, cualificados y con experiencia.</h2><p>Profesionales bilingües oficialmente cualificados y con experiencia en la enseñanza del inglés como segunda lengua. Un equipo que acompaña el progreso del alumno con cercanía, criterio y objetivos claros.</p></section>`);

const matricula=()=>shell('Matrícula',`<section class="enroll-page" data-page-mode="Convert"><div class="wrap enroll-grid"><div class="enroll-copy"><span class="eyebrow light">Matrícula</span><h1>Tu próximo curso puede empezar aquí.</h1><p>El proceso de matriculación de Cosmo School comienza cada año a partir del 1 de abril. Puedes pedir información online, llamar o pasar por cualquiera de los dos centros.</p><div class="enroll-details"><div>${icon('clock')}<span><strong>Apertura de matrícula</strong>A partir del 1 de abril</span></div><div>${icon('phone')}<span><strong>Teléfono</strong>643 349 226</span></div><div>${icon('pin')}<span><strong>Écija</strong>Merinos, 54 · Fuente Nueva, 2</span></div></div></div><div class="enroll-form-card"><h2>Solicita información</h2><p>Déjanos tus datos y dinos qué necesitas.</p>${form()}</div></div></section>`);

const contacto=()=>shell('Contacto',`<section class="contact-hero wrap" data-page-mode="Convert"><span class="eyebrow">Contacto</span><h1>Hablemos de tu inglés.</h1><p>Dos centros en Écija y un equipo dispuesto a orientarte sobre cursos, niveles y matrícula.</p></section><section class="contact-grid wrap"><div class="contact-info"><a href="tel:+34643349226">${icon('phone')}<span><small>Teléfono</small>643 349 226</span></a><a href="mailto:cosmoschool2015@gmail.com">${icon('mail')}<span><small>Email</small>cosmoschool2015@gmail.com</span></a><a href="https://instagram.com/cosmoschool2015" target="_blank">${icon('insta')}<span><small>Instagram</small>@cosmoschool2015</span></a><div>${icon('clock')}<span><small>Recepción</small>Mar–Vie 10:00–12:00<br>Lun–Vie 16:00–20:00</span></div></div><div class="contact-form-box"><h2>Escríbenos</h2>${form()}</div></section><section class="map-cards wrap"><div>${icon('pin')}<h3>C/ Merinos, 54</h3><iframe title="Mapa Merinos" src="https://www.google.com/maps?q=C%2F%20Merinos%2054%2C%20Ecija&output=embed" loading="lazy"></iframe></div><div>${icon('pin')}<h3>C/ Fuente Nueva, 2</h3><iframe title="Mapa Fuente Nueva" src="https://www.google.com/maps?q=C%2F%20Fuente%20Nueva%202%2C%20Ecija&output=embed" loading="lazy"></iframe></div></section>`);

const legal=()=>shell('Legal',`<section class="legal-page wrap" data-page-mode="Prove"><span class="eyebrow">Información legal</span><h1>Aviso legal y privacidad.</h1><div class="legal-copy"><h2>Aviso legal</h2><p>El sitio web corresponde a Cosmo School. Para cualquier cuestión relacionada con la actividad de la academia o con el uso del sitio, puedes contactar a través de cosmoschool2015@gmail.com.</p><h2 id="privacidad">Política de privacidad</h2><p>Los datos facilitados a través de los formularios se utilizarían únicamente para atender solicitudes de información y matrícula. La versión definitiva incorporará el texto legal actualizado, las bases de legitimación, plazos de conservación y mecanismos de ejercicio de derechos correspondientes.</p><h2 id="cookies">Política de cookies</h2><p>Las cookies no esenciales quedarían bloqueadas hasta obtener consentimiento. El sitio definitivo incluirá un panel de preferencias para aceptar, rechazar o configurar categorías.</p><p class="legal-note">Los textos legales definitivos deberán validarse antes de la publicación del sitio.</p></div></section>`);

export const pages = {
 'index.html':home(),
 'cursos/index.html':cursos(),
 'cambridge/index.html':cambridge(),
 'metodologia/index.html':metodologia(),
 'sobre-nosotros/index.html':nosotros(),
 'matricula/index.html':matricula(),
 'contacto/index.html':contacto(),
 'legal/index.html':legal()
};
